### ISSUE TITLE
Send Message on App Installation 

### ISSUE THREAD

**Issue by samad-yar-khan** [RocketChat/Apps.Github22#110]
## Acceptance Criteria

- [ ] Send message to the Server Admin regarding app installation once its installed on the server.
- [ ] The message should only be sent once to the Admin
- [ ] Message should be welcoming and should have a link to our GitHub for feedback

**Comment by aakash1233333** [comment]
Hii .I want to deal with this issue .
Best 
Aakash

**Comment by aakash1233333** [comment]
Samad sir I have written the code for it .But facing some problems in the setup of server of Rocket.chat and also sir the message will be sent on the app installation . So the code should be written on authentication.ts file ?? Just wanted to confirm .
