### ISSUE TITLE
Bot does not return repo details on a private repo

### ISSUE THREAD

**Issue by DarinDev1000** [RocketChat/Apps.Github22#19]
### Description:

The app installed and I logged in but when using the bot, it doesn't seem to return any details

### Steps to reproduce:

 Install and add OAuth
Login to GitHub
run `DarinDev1000/southwest-flight-list`

### Expected behavior:

Details to return like a public repo

### Actual behavior:

![Screen Shot 2022-08-18 at 5 52 19 PM](https://user-images.githubusercontent.com/43659317/185519239-f0a3c53c-e1fb-4b85-97e7-7b4e930981ad.png)

### Rocket.Chat Server Setup Information:

- Version of Rocket.Chat Server: 5/0/3
- Operating System: ubuntu 22.04
- Deployment Method: docker

### Rocket.Chat Client Setup Information

- Desktop App Version: 
- Browser Version: 
- Operating System: 
- Android App Version: 
- IOS Application Version:

**Comment by samad-yar-khan** [comment]
@DarinDev1000 Thankyou for trying out our app and opening this issue. The repository details for now does not return private repositories. I will look into this and get it fixed ASAP. Let me know if you run into any other bugs, we will try to get them fixed ASAP.
