### ISSUE TITLE
Document code formatting and syntax highlighting design decision

### ISSUE THREAD

**Issue by Sing-Li** [RocketChat/Apps.Github22#2]
The ability to format code and syntax highlight code in different programming language is absolutely essential to the usability of a modern Github App  (circa 2022).

Limitations of the current "apps engine", its rigid binding to a very "chat dedicated" UIKit and Fuselage, makes it especially difficult to add this usable feature.

**Comment by RonLek** [comment]
@samad-yar-khan please let know the progress / link to documentation around this.

**Comment by samad-yar-khan** [comment]
@Sing-Li  @RonLek I have added the documentation for syntax highlighting and code editor integration. Have a look. [Pull Request Reviews : Integrating Code Editor with Syntax Highlighting](https://github.com/RocketChat/Apps.Github22/wiki/Pull-Request-Reviews--:-Integrating-Code-Editor-with-Syntax-Highlighting)

**Comment by Sing-Li** [comment]
Cool.  Thanks.
