### ISSUE TITLE
Expand Code Links 

### ISSUE THREAD

**Issue by samad-yar-khan** [RocketChat/Apps.Github22#26]
## Why do we need this ?

As a GitHub App developer

**I need to**: 
Add a listener for room messages and extend GitHub Code links like - https://github.com/RocketChat/Apps.Github22/blob/main/github/definitions/githubIssueData.ts#L4-L9 
**So That**:
Users can see the linked code segment ins the sent message.
## Acceptance Criteria

- [ ] Add listener for room messages which contain GitHub Code Segment link
- [ ] Extend the message to contain the linked code.

## Further Comments / References  

- [Documentation](https://rocketchat.github.io/Rocket.Chat.Apps-engine/modules/messages_ipremessagesentextend.html)
- Inspiration : 
![image](https://user-images.githubusercontent.com/70485812/195501620-759602d0-ba47-4939-8caf-aadb56f902f7.png)

**Comment by mohitbalwani** [comment]
I would like to work on this issue. Can anyone assign it to me?

**Comment by Nabhag8848** [comment]
Hey @mohitbalwani, are you working around this?
