### ISSUE TITLE
[BUG] Interactive Buttons Giving Unexpected Results When Provided Repository in Command doesn't exist

### ISSUE THREAD

**Issue by Nabhag8848** [RocketChat/Apps.Github22#40]
### Description:

- By executing `/github Username/RepositoryName` and if the Provided **Username/RepositoryName** doesn't exist. Interacting with Actions Buttons giving unexpected outputs. Specially when interacting with `Overview` Action Button giving undefined in several places more precisely in following: 
     
       1. Username/Repository
       2. Number of Stars
       3. Number of Issues
       4. Number of Forks
       5. Description

- User might make `Typo` when using commands and this would lead to above unexpected result.

### For Example: 

- By executing `/github Rocket.Chat/Rocket.Chat` and then interacting with the Overview Button Specially will lead to problem specified above as there is no Username/Org matching `Rocket.Chat`. 

### Steps to reproduce:

1. Run command `/github Username/RepositoryName` by having Fake **username/repository**  which doesn't exist in Github. 
2. Interact with Action Buttons Specially `Overview`.
3. check the undefined results.

### Expected behavior:
-  What we actually can do, **Check if the repository exist before showing the action buttons**. Only show the Action Buttons if the `repository` exists and now instead of sending `Hey {username}!` via bot everytime before we show the Buttons.Now, if the repository doesn't exist we will avoid showing ActionButtons and Send the message `Hey { username } ! Provided username and/or repository doesn't exist `. and in case of everything goes fine meaning repository exist will show the Buttons as well as the text `Hey {username}!`.

 ![Screenshot from 2022-12-05 21-01-09](https://user-images.githubusercontent.com/65061890/205676939-f9d2d66b-0b66-4abf-8ef3-51e0a0f25ead.png)

### Actual behavior:
- As discussed in the **Description** section, you can see the the `undefined` results at several places.

![Screenshot from 2022-12-04 15-12-39](https://user-images.githubusercontent.com/65061890/205680558-15a5f492-a0ad-44bd-a726-d4027ef5c0fe.png)

### Note: 
- [x] Willing to work on the issue.

**Comment by Nabhag8848** [comment]
Hey, I see there are no validation for several other commands too, if the repository doesn't exist we are not getting any response. which is leading to doubt that the command was send/run to user. is it good idea? to send the same validation message `Provided repository doesn't exist` when repository doesn't exist.

**Comment by samad-yar-khan** [comment]
@Nabhag8848 yeah, it seems like a great idea. Thanks a lot for pointing this out
