### ISSUE TITLE
Slash command not working

### ISSUE THREAD

**Issue by Rodriq** [RocketChat/Apps.Github22#46]
### Description:

The slash command `/github issues` with "S" when sent, nothing happens

### Steps to reproduce:

- Install the app
- Authenticate
- run /github issues

### Expected behavior:

SOmething

### Actual behavior:

Nothing, just gives list of commands

Uploading 13.02.2023_18.12.37_REC.mp4…

### Rocket.Chat Server Setup Information
Latest atm

**Comment by Nabhag8848** [comment]
Hey @Rodriq , Thanks for opening an issue. we do have discussion and find out the cause, we already have PR #42 which solves this issue.

**Comment by Rodriq** [comment]
Confirmed
