### ISSUE TITLE
Document approach to extend UIKit to support ACE

### ISSUE THREAD

**Issue by RonLek** [RocketChat/Apps.Github22#5]
As a GitHub app developer
**I Need to:** document initial approach to extend UIKit to support ACE editor
**So That:** I can highlight code syntax directly within the app.

**Acceptance Criteria**
Documentation with following sections:
- [ ] Context: Explain context of the problem.
- [ ] Approaches Tried: Explain what approaches have been tried and tested.
- [ ] Blockers: Any blockers in the way of implementing this and how they can be resolved.
- [ ] Decision: What approach was chosen to be the solution.

**Comment by RonLek** [comment]
@samad-yar-khan please take a look at the above acceptance criteria and share the link to the wiki page when done. Thanks.

**Comment by samad-yar-khan** [comment]
@RonLek I believe this issue overlaps with #2  . The documentation for the current progress for the `Code Editor` Integration with our current progress can be found over [here](https://github.com/RocketChat/Apps.Github22/wiki/Pull-Request-Reviews---Editor-Integration). with all ideas and roadblocks. The syntax highlighting can be solved once we have an ACE  Editor component, for now we are focusing on adding a larger `MultiltineInputBlock` which can be useful to other RC Apps aswell. [PR Link](https://github.com/RocketChat/fuselage/pull/766)

**Comment by samad-yar-khan** [comment]
@RonLek I have updated the [Code Editor Integration Documentation](https://github.com/RocketChat/Apps.Github22/wiki/Pull-Request-Reviews--:-Integrating-Code-Editor-with-Syntax-Highlighting) and have included all of our progress and research on fuselage and Apps-engine.

**Comment by Sing-Li** [comment]
![image](https://user-images.githubusercontent.com/122633/189530258-e84c74d8-257f-4cca-b8c5-160b65530b97.png)

Looks good.  Closing.  Thx.
