### ISSUE TITLE
Hooks integration to fetch issues and PRs.

### ISSUE THREAD

**Issue by RonLek** [RocketChat/Apps.Github22#6]
As a GitHub app developer
**I Need to:** create webhooks for GitHub API
**So That:** I can fetch issues and PRs directly within Rocket.Chat

**Acceptance Criteria**
- [x] Document the approach taken with diagrams for user flow.

**Comment by samad-yar-khan** [comment]
@RonLek  I have added the workflow and how the works along with some code explanations in the [Wiki](https://github.com/RocketChat/Apps.Github22/wiki/GitHub-Event-Subscriptions).

**Comment by RonLek** [comment]
Thanks @samad-yar-khan . Could you please confirm if #7  already added this one so I can mark this as complete?

**Comment by samad-yar-khan** [comment]
@RonLek It was not part of the pull request but I have added the documentation to project wiki : [https://github.com/RocketChat/Apps.Github22/wiki/GitHub-Event-Subscriptions](GitHub event subscription user flow). Let me know if anything else is requires :)

**Comment by RonLek** [comment]
LGTM
