### ISSUE TITLE
Spelling Errors 

### ISSUE THREAD

**Issue by samad-yar-khan** [RocketChat/Apps.Github22#66]
### Description:

- During the development of the app, there were some spelling errors which went unnoticed.  These include spelling errors like Subsciption, Reqeust etc. 
- There should ideally be no spelling errors in the app.

**Comment by VipinDevelops** [comment]
Hey sir can i take this issue, 
I would love to fix all the spelling errors in the code and will try to add some comments, in places where it's needed. 
Thank you.

**Comment by samad-yar-khan** [comment]
@VipinDevelops  assigned. All the best :)

**Comment by VipinDevelops** [comment]
@samad-yar-khan  This issue is now resolved sir we can remove it.

**Comment by samad-yar-khan** [comment]
Thanks @VipinDevelops . Closing it now. :)
