### ISSUE TITLE
[BUG] missing i18n for english causing the description of command with extra removable string

### ISSUE THREAD

**Issue by Nabhag8848** [RocketChat/Apps.Github22#70]
### Description:
- When running any command `/github`, it shows the description of the command  with the id of an App in form `apps-<appid>-DESCRIPTION` and the cause of the same is we don't have provided any i18n string of any language. Thus we need the i18n translation for english language for the Description and Params of command (i18nDescription && i18nParamsExample) under gh and github command class.

### Steps to reproduce:

1.  run `/github`
2.  check the output with the description

### Expected behavior:
- Provide i18n for both, by creating folder i18n and naming the file en.json to resolve the issue

### Actual behavior:
![Screenshot from 2023-03-20 13-29-20](https://user-images.githubusercontent.com/65061890/226282477-a299aa6e-a546-492d-98bc-5a0e2c956e10.png)

**Comment by joeshajan** [comment]
So what will the end result look like?

![Screenshot 2023-03-23 081834](https://user-images.githubusercontent.com/69904519/227087860-770e5925-c629-4b26-9f4d-2eaf2b76ddbd.png)

What I'm assuming is instead of this id☝️ there must be something else. Am I right?

**Comment by Nabhag8848** [comment]
> So what will the end result look like?
> 
> ![Screenshot 2023-03-23 081834](https://user-images.githubusercontent.com/69904519/227087860-770e5925-c629-4b26-9f4d-2eaf2b76ddbd.png)
> 
> What I'm assuming is instead of this idpoint_up there must be something else. Am I right?

Hey @samad-yar-khan do we need the description as "fetching github data"  or we need changes? 
Can you provide the description and paramsexample string we need to have in translation. As i see @joeshajan is looking forward to contribute to rhis issue.

**Comment by samad-yar-khan** [comment]
@Nabhag8848 @joeshajan So, This should ideally include some short description of the app
