### ISSUE TITLE
Github login does not work 

### ISSUE THREAD

**Issue by kanishbodhwani** [RocketChat/Apps.Github22#71]
### Steps to reproduce:

1. Write the command /github login in any chat window 

### Expected behavior:

It should login to my github account 

### Actual behavior:

Its redirecting to a 404 not found page 
<img width="1417" alt="error" src="https://user-images.githubusercontent.com/64742906/227030399-a9b395b8-b726-429b-a75d-8a85ae77ae9c.png">

**Comment by kanishbodhwani** [comment]
Closed

**Comment by WaldemarEnns** [comment]
Having the same issue here - what was the solution?
