### ISSUE TITLE
Slash command misbehaves when fully typed

### ISSUE THREAD

**Issue by Rodriq** [RocketChat/Apps.Github22#84]
### Description:

When you manually type the `/github <something>` slash command without using the suggestion, when you press enter you get `github` appended to the command again.

### Steps to reproduce:

1. Install and configure the app
2. In any channel, type for example the slash command `/github me` completely without taking any suggestion
3. Press enter

### Expected behavior:

Normal user info should show or whatever the command is meant for should show

### Actual behavior:

You get `github` appended to the slash command

### Rocket.Chat Server Setup Information:

- Version of Rocket.Chat Server: 6.0.1
- Operating System: Windows
- Deployment Method: Docker on AWS

### Rocket.Chat Client Setup Information

Desktop app on windows

### Additional context

See the screen recording below. I used an onscreen keyboard so you can see everything completely.

https://user-images.githubusercontent.com/39289592/228433685-286f96b3-8065-485d-9664-18057f8e4bce.mp4

**Comment by Nabhag8848** [comment]
Hey @Rodriq This issue is related to RC and this is happening for every slashcommand we are running regardless of app.
- we have a open issue for same https://github.com/RocketChat/Rocket.Chat/issues/28473

**Comment by ggazzo** [comment]
duplicated of #28473
